apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-api
  labels:
    app: {{ .Release.Name }}-api
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-api
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-api
    spec:
      containers:
        - name: api
          image: {{ .Values.api.image }}
          ports:
            - containerPort: {{ .Values.api.port }}
          env:
            - name: TEMPORAL_ADDRESS
              value: {{ .Values.temporal.address }}
            - name: TEMPORAL_NAMESPACE
              value: {{ .Values.temporal.namespace }}
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
