apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-worker
  labels:
    app: {{ .Release.Name }}-worker
spec:
  replicas: {{ .Values.worker.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-worker
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-worker
    spec:
      containers:
        - name: worker
          image: {{ .Values.worker.image }}
          env:
            - name: TEMPORAL_ADDRESS
              value: {{ .Values.temporal.address }}
            - name: TEMPORAL_NAMESPACE
              value: {{ .Values.temporal.namespace }}
